### ISSUE TITLE
Implement Settings 

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-ui#141]
- [ ] Market Making Bot
- [x] Initial Setup
- [x] Backup
- [x] Change Password
- [ ] Asset Denomination
- [ ] About

**Comment by kilrau** [comment]
Moved this to 1.3.0 since settings is needed for https://github.com/ExchangeUnion/xud-ui/issues/39

**Comment by krrprr** [comment]
**Notes on choosing a backup directory**

Discord discussion summary:

Focus will be on local connection for now since remote is relatively an edge case. Yang Yang is working on a new binary launcher that will give xud-explorer read and write access to the remote filesystem. In this milestone, we can focus on getting the local backup file setup right and remote backup tab can be disabled for now.

**Comment by peartobear** [comment]
Update discord discussion:

- Path cannot be accessed via browser because of security reasons 

- Launcher has full file system access and can verify the typed path 

- But launcher cannot expose the file system path picker to browser because of security concerns (in theory it can since it has full access)

So we decided to go with text field path entry UI for the browsers and wherever path isn’t accessible. File picker path entry UI for rest of the cases. Corresponding Figma wireframe is updated with the new screen `settings backup text field"
