### ISSUE TITLE
Shutdown functionality improvements

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud-ui#147]
1. for now shutdown notification appears in both cases  (local env/remote env) - it should appear only for local env. (and local env should not be shut downed if i connected to remote env)
2. change `Shutdown` to `Quit` for not local env cases (when I have remote connected env or just not connected to env).
3. Shutdown notification appears for testnet setup, but there is no shutdown after that - make shutdown work for testnet/simnet (network type can be retrieved from getinfo call of xud)

**Comment by krrprr** [comment]
Would make sense to start with this after https://github.com/ExchangeUnion/xud-ui/issues/112 is done and all operating systems are using the launcher for local environment.

One thing to consider: the user can change their connection during the app lifetime. If an environment was brought up by the app, it should be taken down by the app even if at the time of closing a remote connection is established or no connection is active at all (user went back to the landing page, for instance). With local -> remote switch it can still be confusing (not a very probable real life use case, though).

Currently, with xud-ui + launcher it is only possible to bring up mainnet. imho xud-ui should not take down any environment that was not brought up by the xud-ui.

My suggestion:
- the xud-ui remembers if has started a local (currently only mainnet) environment;
- if so, the shutdown is displayed in the menu (otherwise quit) and the according messages appear on closing window / quitting the app. Otherwise no messages (?)

@raladev @kilrau wdyt? anything else to consider?

**Comment by kilrau** [comment]
> Would make sense to start with this after #112 is done and all operating systems are using the launcher for local environment.

Ok

>  the user can change their connection during the app lifetime. If an environment was brought up by the app, it should be taken down by the app even if at the time of closing a remote connection is established or no connection is active at all 

Agreed

> My suggestion:
>     the xud-ui remembers if it has started a local (currently only mainnet) environment;
>     if so, the shutdown is displayed in the menu (otherwise quit) and the according messages appear on closing window / quitting the app. Otherwise no messages (?). On app close, the local mainnet environment is shut down.

Sounds good, but please prepare already for simnet which we plan to make accessible via https://github.com/ExchangeUnion/xud-ui/issues/138.

> This also leads me thinking of the `Disconnect` button. Would just throw a thought in the air, would make sense to deal with it separately. Currently the local env is not shut down when the `Disconnect` is clicked. Not sure if it's so obvious... Maybe we could add two options/variants for that button - one would just disconnect and the other shuts down the env. Something in that style:
> ![Screenshot from 2020-12-22 16-48-43](https://user-images.githubusercontent.com/24500376/102901035-ce6c5280-4475-11eb-9d0b-da5c078500e1.png)

Not sure, wdyt @peartobear

**Comment by krrprr** [comment]
I suggest removing the window closing message on macOS as the default behavior of the apps there is anyway like this: the apps are not closed when its window(s) is/are closed and they remain in the dock unless `cmd + q` or `quit` is done. I personally found the messages rather confusing and disturbing on macOS. The shutdown message is ok I guess. @peartobear wdyt?

**Comment by peartobear** [comment]
> I suggest removing the window closing message on macOS as the default behavior of the apps there is anyway like this: the apps are not closed when its window(s) is/are closed and they remain in the dock unless cmd + q or quit is done. I personally found the messages rather confusing and disturbing on macOS. The shutdown message is ok I guess. @peartobear wdyt?

True, windows close works as "minimize" on MacOS, unless explicitly shut down. I like the idea of having dropdown options, where one option can normally disconnect or sleep while the second option will shut down as you said

**Comment by peartobear** [comment]
Discord discussion summary:

Focus will be on local connection for now since remote is relatively an edge case. Yang Yang is working on a new binary launcher that will give xud-explorer read and write access to the remote filesystem. In this milestone, we can focus on getting the local backup file setup right and remote backup tab can be disabled for now.
