### ISSUE TITLE
Enforce WSL2 (Can't run docker on Windows 10 Home with Hyper-V)

### ISSUE THREAD

**Issue by JoPark20** [ExchangeUnion/xud-ui#96]
I installed xud ui, downloaded docker and installed docker, rebooted - so far all good.
But as i am using windows 10 **home** i can't get docker running, see pop up:
![Screenshot (24)](https://user-images.githubusercontent.com/43677783/98444890-b7b3ab80-2114-11eb-80ed-4a8ecffcf9d0.png)
this leads to en ever loading xud screen:
![Screenshot (25)](https://user-images.githubusercontent.com/43677783/98444919-de71e200-2114-11eb-956f-fca4f8cc11ab.png)

**Comment by kilrau** [comment]
Thanks for opening this issue! This is not related to Windows Home (docker works fine on Windows home, see https://docs.docker.com/docker-for-windows/install-windows-home/), but that your computer's motherboard has hardware virtualization switched off. You will need to enable it via the BIOS menu. I can help you with this on discord in a 1-1 session.

Since unfortunately there is nothing much we can do to "fix" it, I wonder what computer motherboard you have. I was convinced most modern motherboards have virtualization enabled by default :/

**Comment by JoPark20** [comment]
Ah thanks for the additional information - I got the link (same from screenshot: https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization), which lead my to Hyper V.. And here I read about that this feature is only available for Windows Enterprise / Pro.
Will write you this evening tomorrow the specs.

**Comment by kilrau** [comment]
Thanks for reporting back. Here is the problem:
- Docker needed Hyper-V to be enabled to work up until the official release of WSL2 in May this year.
- Docker refers to WSL2 as "default" now and Hyper-V as "legacy" backend.
- Windows 10 Home does not include Hyper-V, [but it **does include WSL2**](https://docs.docker.com/docker-for-windows/install-windows-home/)
- WSL2 is supported from Windows 10 version 1903 already, which everyone should be running by now


Since on top of all that, WSL2 is much more stable for our linux containers, I think it's time to force Hyper-V out.

Todo's for this issue:
Step 1. Disable Hyper-V fallback and **always** bring up WSL2 installation (even though that means opening a browser tab asking user to download the WSL2 exe and install it manually). I closed https://github.com/ExchangeUnion/xud-ui/issues/87.
Step 2: Detect if Virtualization is not enabled, there must be a Windows System call for that, it's shown in the taskmanager's performance tab:
![image](https://user-images.githubusercontent.com/19181985/98523390-2b20fe80-2276-11eb-9718-2f6af4ea3b90.png)
Step 3: Continue investigating how an unattended WSL2 installation could be achieved: I found microsoft/WSL#3369 and opened microsoft/WSL#6201

**Comment by kilrau** [comment]
Watch https://github.com/microsoft/WSL/discussions/6201#event-13453

**Comment by kilrau** [comment]
So [downloading the WSL2.exe and installing via Powershell is already possible](https://github.com/microsoft/WSL/discussions/6201#discussioncomment-130889), just that the user would need confirm an admin prompt. Let's give this a shot @erkarl
